// Device Tree Source (DTS) Generator
// Converts application state into properly formatted DTS code

/**
 * Generate complete DTS file from application state
 * @param {Object} state - { board, nodes: [{ name, enabled, phyAddr, pathway }] }
 * @returns {string} - Formatted DTS code
 */
export function generateDTS(state) {
  if (!state || !state.board || !state.nodes || state.nodes.length === 0) {
    return '// Select a board and configure ethernet nodes to generate DTS';
  }

  const enabledNodes = state.nodes.filter(n => n.enabled);
  if (enabledNodes.length === 0) {
    return '// Enable at least one ethernet node to generate DTS';
  }

  let dts = `/dts-v1/;\n\n`;
  dts += `/* Device Tree for ${state.board} */\n`;
  dts += `/* Auto-generated by Device Tree Architect */\n\n`;
  dts += `/ {\n`;
  dts += `\tmodel = "${state.board}";\n`;
  dts += `\tcompatible = "xlnx,zynqmp";\n\n`;
  dts += `\t/* Enabled Ethernet Nodes */\n`;

  enabledNodes.forEach((node, index) => {
    if (index > 0) dts += '\n';
    dts += formatEthernetNode(node);
  });

  dts += `};\n`;
  return dts;
}

/**
 * Format single ethernet node to DTS
 */
function formatEthernetNode(node) {
  let result = `\t${node.name} {\n`;
  result += `\t\tcompatible = "${node.compatible || 'cdns,gem'}";\n`;
  result += `\t\tstatus = "${node.status || 'okay'}";\n`;
  
  if (node.reg) {
    result += `\t\treg = <${node.reg}>;\n`;
  }
  
  result += `\t\tphy-mode = "${node.phyMode || 'rgmii-id'}";\n`;
  
  if (node.phyAddr) {
    result += `\t\t#address-cells = <1>;\n`;
    result += `\t\t#size-cells = <0>;\n\n`;
    result += `\t\t/* PHY Configuration - ${node.pathway || 'MIO'} Path */\n`;
    result += `\t\tethernet-phy@${node.phyAddr.toString(16)} {\n`;
    result += `\t\t\treg = <0x${node.phyAddr.toString(16)}>;\n`;
    result += `\t\t};\n`;
  }
  
  result += `\t};\n`;
  return result;
}

/**
 * Generate Mermaid diagram from application state
 * @param {Object} state - Application state
 * @returns {string} - Mermaid diagram code
 */
export function renderMermaid(state) {
  if (!state || !state.board || !state.nodes || state.nodes.length === 0) {
    return `graph TD
    A[Select Board] --> B[Configure Ethernet]
    style A fill:#764ba2,stroke:#fff,color:#fff`;
  }

  const enabledNodes = state.nodes.filter(n => n.enabled);
  if (enabledNodes.length === 0) {
    return `graph TD
    Board[${state.board}] --> |No Nodes Enabled| Configure
    style Board fill:#764ba2,stroke:#fff,color:#fff`;
  }

  let mermaid = `graph LR\n`;
  mermaid += `    PS[Processing System<br/>${state.board}]\n`;

  enabledNodes.forEach((node, index) => {
    const nodeId = `GEM${index}`;
    const phyId = `PHY${index}`;
    const pathway = node.pathway || 'MIO';
    const color = getPathwayColor(pathway);
    
    mermaid += `    ${nodeId}[${node.name}<br/>PHY: 0x${(node.phyAddr || 0).toString(16)}]\n`;
    mermaid += `    ${phyId}[Ethernet PHY]\n`;
    mermaid += `    PS -->|${pathway}| ${nodeId}\n`;
    mermaid += `    ${nodeId} -->|${node.phyMode || 'rgmii-id'}| ${phyId}\n`;
    mermaid += `    style ${nodeId} fill:${color},stroke:#fff,color:#fff\n`;
  });

  mermaid += `    style PS fill:#764ba2,stroke:#fff,color:#fff\n`;
  return mermaid;
}

/**
 * Get color for pathway badge
 */
function getPathwayColor(pathway) {
  const colors = {
    'MIO': '#51cf66',
    'EMIO': '#f5576c',
    'GTR': '#3949ab'
  };
  return colors[pathway] || '#667eea';
}
